[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time32"]

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time32"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["--cfg", "espidf_time32"]

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
ESP_IDF_SYS_ROOT_CRATE = { value = "micro-rdk-server" }
