name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  
  publish-installer-release:
    needs: tests
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, exe: amd64-linux, os: ubuntu-latest }
          - { target: aarch64-unknown-linux-gnu, exe: aarch64-linux, os: ubuntu-latest }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, exe: windows.exe, os: windows-latest }
    runs-on: ${{ matrix.job.os }}
    env:
      working-directory: ./micro-rdk-installer
    steps:
    - name: Checkout main branch code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
      working-directory: ${{ env.working-directory }}
    - name: Set toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.67.0
        override: true
        target: ${{ matrix.job.target }}
      working-directory: ${{ env.working-directory }}
    - name: Build installer binary
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        args: --release --target=${{ matrix.job.target }}
        command: build
      working-directory: ${{ env.working-directory }}
    - name: Rename result
      run: |
        rm target/${{ matrix.job.target }}/release/micro-rdk-installer.d
        cp target/${{ matrix.job.target }}/release/micro-rdk-installer* micro-rdk-installer-${{ matrix.job.exe }}
        sha256sum  micro-rdk-installer-${{ matrix.job.exe }}  >> sha256sums.txt
      working-directory: ${{ env.working-directory }}
    - name: Check release type
      id: check-tag
      run: |
        if echo ${{ github.event.ref }} | grep -Eq '^refs/tags/v.*rc[0-9]{1}$'; then
              echo "match=true" >> $GITHUB_OUTPUT
        else
              echo "match=false" >> $GITHUB_OUTPUT
        fi
      working-directory: ${{ env.working-directory }}
    - name: Publish installer release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          micro-rdk-installer-${{ matrix.job.exe }}
          sha256sums.txt
        prerelease: ${{ steps.check-tag.outputs.match }}
      working-directory: ${{ env.working-directory }}
      

  publish-release:
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/micro-rdk-dev-env:amd64
    needs: tests
    steps:
    - name : Checkout main branch code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Build esp32 binary
      run: |
        bash -c 'export MICRO_RDK_USE_NVS=true && . "$IDF_PATH"/export.sh && . "$ESP_ROOT"/export-esp.sh && make build-esp32-with-cred-bin'
        cp examples/target/esp32-server-with-cred.bin  micro-rdk-esp32-server.bin
        sha256sum  micro-rdk-esp32-server.bin  >> sha256sums.txt
    - name: Check release type
      id: check-tag
      run: |
        if echo ${{ github.event.ref }} | grep -Eq '^refs/tags/v.*rc[0-9]{1}$'; then
              echo "match=true" >> $GITHUB_OUTPUT
        else
              echo "match=false" >> $GITHUB_OUTPUT
        fi
    - name: Publish release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          micro-rdk-esp32-server.bin
          sha256sums.txt
        prerelease: ${{ steps.check-tag.outputs.match }}
